# mostly copied from https://github.com/zebreus/nix-website-example/blob/master/.github/workflows/pages.yml
name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v26
        with:
          nix_conf: experimental-features = nix-command flakes

      - name: Activate Flake Outputs
        id: flake-outputs
        run: |
          echo "outputs=$(nix flake show --json)" >> $GITHUB_OUTPUT

      - name: Setup Pages
        uses: actions/configure-pages@v

      - name: Build Website
        run: |
          nix build .

      - name: Adjust permissions
        run: |
          chown -R `id -u`:`id -g` ./result
          chmod -R a+rwx ./result

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./result

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      
